// <auto-generated />
using System;
using GestionProyectosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProyectosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241005051731_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionProyectosAPI.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Equipo encargado de la programación y desarrollo de software.",
                            Nombre = "Desarrollo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Equipo encargado del diseño gráfico y experiencia de usuario.",
                            Nombre = "Diseño"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Equipo encargado de la infraestructura y soporte operativo.",
                            Nombre = "Operaciones"
                        });
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipoId = 1,
                            FechaFin = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Plataforma Interna"
                        },
                        new
                        {
                            Id = 2,
                            EquipoId = 1,
                            FechaFin = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sistema de Automatización"
                        },
                        new
                        {
                            Id = 3,
                            EquipoId = 1,
                            FechaFin = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Migración de Plataforma"
                        },
                        new
                        {
                            Id = 4,
                            EquipoId = 2,
                            FechaFin = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Rediseño Web Corporativo"
                        },
                        new
                        {
                            Id = 5,
                            EquipoId = 2,
                            FechaFin = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Identidad Visual Nueva Marca"
                        },
                        new
                        {
                            Id = 6,
                            EquipoId = 2,
                            FechaFin = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Diseño de Aplicación Móvil"
                        },
                        new
                        {
                            Id = 7,
                            EquipoId = 3,
                            FechaFin = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Optimización de Redes"
                        },
                        new
                        {
                            Id = 8,
                            EquipoId = 3,
                            FechaFin = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Automatización de Servidores"
                        },
                        new
                        {
                            Id = 9,
                            EquipoId = 3,
                            FechaFin = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Migración de Datos a Nube"
                        });
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Planificación inicial",
                            Estado = "Pendiente",
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Desarrollo de prototipos",
                            Estado = "EnProgreso",
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Implementación de módulos",
                            Estado = "Pendiente",
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pruebas de integración",
                            Estado = "Pendiente",
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Despliegue inicial",
                            Estado = "Pendiente",
                            ProyectoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Recolección de requerimientos",
                            Estado = "Pendiente",
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Diseño del sistema",
                            Estado = "Pendiente",
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Configuración de servidores",
                            Estado = "EnProgreso",
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Pruebas de rendimiento",
                            Estado = "Pendiente",
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Lanzamiento del sistema",
                            Estado = "Pendiente",
                            ProyectoId = 2
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Evaluación de la plataforma actual",
                            Estado = "Pendiente",
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Planificación de migración",
                            Estado = "EnProgreso",
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Implementación del nuevo sistema",
                            Estado = "Pendiente",
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Transferencia de datos",
                            Estado = "Pendiente",
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Pruebas finales",
                            Estado = "Pendiente",
                            ProyectoId = 3
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Investigación de usuario",
                            Estado = "Pendiente",
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Creación de wireframes",
                            Estado = "Pendiente",
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Diseño de interfaz de usuario",
                            Estado = "EnProgreso",
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Implementación de prototipos",
                            Estado = "Pendiente",
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Pruebas de usabilidad",
                            Estado = "Pendiente",
                            ProyectoId = 4
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Desarrollo de conceptos",
                            Estado = "Pendiente",
                            ProyectoId = 5
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Diseño de logo",
                            Estado = "Pendiente",
                            ProyectoId = 5
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Creación de guías de estilo",
                            Estado = "EnProgreso",
                            ProyectoId = 5
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Elaboración de material promocional",
                            Estado = "Pendiente",
                            ProyectoId = 5
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Presentación al cliente",
                            Estado = "Pendiente",
                            ProyectoId = 5
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Diseño de pantallas",
                            Estado = "Pendiente",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Creación de iconografía",
                            Estado = "Pendiente",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 28,
                            Descripcion = "Pruebas de diseño",
                            Estado = "Pendiente",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 29,
                            Descripcion = "Adaptación a diferentes dispositivos",
                            Estado = "EnProgreso",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 30,
                            Descripcion = "Revisión final de diseño",
                            Estado = "Pendiente",
                            ProyectoId = 6
                        },
                        new
                        {
                            Id = 31,
                            Descripcion = "Auditoría de infraestructura",
                            Estado = "Pendiente",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 32,
                            Descripcion = "Revisión de configuraciones actuales",
                            Estado = "Pendiente",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 33,
                            Descripcion = "Implementación de mejoras",
                            Estado = "EnProgreso",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 34,
                            Descripcion = "Pruebas de conectividad",
                            Estado = "Pendiente",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 35,
                            Descripcion = "Documentación de cambios",
                            Estado = "Pendiente",
                            ProyectoId = 7
                        },
                        new
                        {
                            Id = 36,
                            Descripcion = "Configuración de herramientas",
                            Estado = "Pendiente",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 37,
                            Descripcion = "Desarrollo de scripts de automatización",
                            Estado = "Pendiente",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 38,
                            Descripcion = "Pruebas de integración",
                            Estado = "EnProgreso",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 39,
                            Descripcion = "Documentación del proceso",
                            Estado = "Pendiente",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 40,
                            Descripcion = "Implementación en producción",
                            Estado = "Pendiente",
                            ProyectoId = 8
                        },
                        new
                        {
                            Id = 41,
                            Descripcion = "Selección de plataforma",
                            Estado = "Pendiente",
                            ProyectoId = 9
                        },
                        new
                        {
                            Id = 42,
                            Descripcion = "Planificación de migración",
                            Estado = "Pendiente",
                            ProyectoId = 9
                        },
                        new
                        {
                            Id = 43,
                            Descripcion = "Transferencia de datos",
                            Estado = "EnProgreso",
                            ProyectoId = 9
                        },
                        new
                        {
                            Id = 44,
                            Descripcion = "Configuración de seguridad",
                            Estado = "Pendiente",
                            ProyectoId = 9
                        },
                        new
                        {
                            Id = 45,
                            Descripcion = "Pruebas y ajustes finales",
                            Estado = "Pendiente",
                            ProyectoId = 9
                        });
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Proyecto", b =>
                {
                    b.HasOne("GestionProyectosAPI.Models.Equipo", "Equipo")
                        .WithMany("Proyectos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Tarea", b =>
                {
                    b.HasOne("GestionProyectosAPI.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Equipo", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("GestionProyectosAPI.Models.Proyecto", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
